modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="MIT License"
[[mods]] #mandatory
modId="nightskippervotemod" #mandatory
version="1.0.0" #mandatory
displayName="Night Skipper Vote Mod" #mandatory
authors="Yutaro Hirayama" #optional
description='''This mod allows players to skip the night in Minecraft through voting.'''
[[dependencies.nightskippervotemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.nightskippervotemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
